// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *Globals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}
