/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestinationOAuthRedirect = {
  /**
   * Redirect URL for OAuth flow if applicable during destination update.
   */
  redirectUrl?: string | undefined;
};

/** @internal */
export const DestinationOAuthRedirect$inboundSchema: z.ZodType<
  DestinationOAuthRedirect,
  z.ZodTypeDef,
  unknown
> = z.object({
  redirect_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "redirect_url": "redirectUrl",
  });
});

/** @internal */
export type DestinationOAuthRedirect$Outbound = {
  redirect_url?: string | undefined;
};

/** @internal */
export const DestinationOAuthRedirect$outboundSchema: z.ZodType<
  DestinationOAuthRedirect$Outbound,
  z.ZodTypeDef,
  DestinationOAuthRedirect
> = z.object({
  redirectUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    redirectUrl: "redirect_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationOAuthRedirect$ {
  /** @deprecated use `DestinationOAuthRedirect$inboundSchema` instead. */
  export const inboundSchema = DestinationOAuthRedirect$inboundSchema;
  /** @deprecated use `DestinationOAuthRedirect$outboundSchema` instead. */
  export const outboundSchema = DestinationOAuthRedirect$outboundSchema;
  /** @deprecated use `DestinationOAuthRedirect$Outbound` instead. */
  export type Outbound = DestinationOAuthRedirect$Outbound;
}

export function destinationOAuthRedirectToJSON(
  destinationOAuthRedirect: DestinationOAuthRedirect,
): string {
  return JSON.stringify(
    DestinationOAuthRedirect$outboundSchema.parse(destinationOAuthRedirect),
  );
}

export function destinationOAuthRedirectFromJSON(
  jsonString: string,
): SafeParseResult<DestinationOAuthRedirect, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestinationOAuthRedirect$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestinationOAuthRedirect' from JSON`,
  );
}
