/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TenantToken = {
  /**
   * JWT token scoped to the tenant for safe browser API calls.
   */
  token?: string | undefined;
};

/** @internal */
export const TenantToken$inboundSchema: z.ZodType<
  TenantToken,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string().optional(),
});

/** @internal */
export type TenantToken$Outbound = {
  token?: string | undefined;
};

/** @internal */
export const TenantToken$outboundSchema: z.ZodType<
  TenantToken$Outbound,
  z.ZodTypeDef,
  TenantToken
> = z.object({
  token: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TenantToken$ {
  /** @deprecated use `TenantToken$inboundSchema` instead. */
  export const inboundSchema = TenantToken$inboundSchema;
  /** @deprecated use `TenantToken$outboundSchema` instead. */
  export const outboundSchema = TenantToken$outboundSchema;
  /** @deprecated use `TenantToken$Outbound` instead. */
  export type Outbound = TenantToken$Outbound;
}

export function tenantTokenToJSON(tenantToken: TenantToken): string {
  return JSON.stringify(TenantToken$outboundSchema.parse(tenantToken));
}

export function tenantTokenFromJSON(
  jsonString: string,
): SafeParseResult<TenantToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TenantToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TenantToken' from JSON`,
  );
}
