/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Awss3Config,
  Awss3Config$inboundSchema,
  Awss3Config$Outbound,
  Awss3Config$outboundSchema,
} from "./awss3config.js";
import {
  Awss3Credentials,
  Awss3Credentials$inboundSchema,
  Awss3Credentials$Outbound,
  Awss3Credentials$outboundSchema,
} from "./awss3credentials.js";
import {
  Topics,
  Topics$inboundSchema,
  Topics$Outbound,
  Topics$outboundSchema,
} from "./topics.js";

/**
 * Type of the destination.
 */
export const DestinationAwss3Type = {
  AwsS3: "aws_s3",
} as const;
/**
 * Type of the destination.
 */
export type DestinationAwss3Type = ClosedEnum<typeof DestinationAwss3Type>;

export type DestinationAwss3 = {
  /**
   * Control plane generated ID or user provided ID for the destination.
   */
  id: string;
  /**
   * Type of the destination.
   */
  type: DestinationAwss3Type;
  /**
   * "*" or an array of enabled topics.
   */
  topics: Topics;
  /**
   * ISO Date when the destination was disabled, or null if enabled.
   */
  disabledAt: Date | null;
  /**
   * ISO Date when the destination was created.
   */
  createdAt: Date;
  config: Awss3Config;
  credentials: Awss3Credentials;
  /**
   * A human-readable representation of the destination target (bucket and region). Read-only.
   */
  target?: string | undefined;
  /**
   * A URL link to the destination target (AWS Console link to the bucket). Read-only.
   */
  targetUrl?: string | null | undefined;
};

/** @internal */
export const DestinationAwss3Type$inboundSchema: z.ZodNativeEnum<
  typeof DestinationAwss3Type
> = z.nativeEnum(DestinationAwss3Type);

/** @internal */
export const DestinationAwss3Type$outboundSchema: z.ZodNativeEnum<
  typeof DestinationAwss3Type
> = DestinationAwss3Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationAwss3Type$ {
  /** @deprecated use `DestinationAwss3Type$inboundSchema` instead. */
  export const inboundSchema = DestinationAwss3Type$inboundSchema;
  /** @deprecated use `DestinationAwss3Type$outboundSchema` instead. */
  export const outboundSchema = DestinationAwss3Type$outboundSchema;
}

/** @internal */
export const DestinationAwss3$inboundSchema: z.ZodType<
  DestinationAwss3,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: DestinationAwss3Type$inboundSchema,
  topics: Topics$inboundSchema,
  disabled_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  config: Awss3Config$inboundSchema,
  credentials: Awss3Credentials$inboundSchema,
  target: z.string().optional(),
  target_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "disabled_at": "disabledAt",
    "created_at": "createdAt",
    "target_url": "targetUrl",
  });
});

/** @internal */
export type DestinationAwss3$Outbound = {
  id: string;
  type: string;
  topics: Topics$Outbound;
  disabled_at: string | null;
  created_at: string;
  config: Awss3Config$Outbound;
  credentials: Awss3Credentials$Outbound;
  target?: string | undefined;
  target_url?: string | null | undefined;
};

/** @internal */
export const DestinationAwss3$outboundSchema: z.ZodType<
  DestinationAwss3$Outbound,
  z.ZodTypeDef,
  DestinationAwss3
> = z.object({
  id: z.string(),
  type: DestinationAwss3Type$outboundSchema,
  topics: Topics$outboundSchema,
  disabledAt: z.nullable(z.date().transform(v => v.toISOString())),
  createdAt: z.date().transform(v => v.toISOString()),
  config: Awss3Config$outboundSchema,
  credentials: Awss3Credentials$outboundSchema,
  target: z.string().optional(),
  targetUrl: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    disabledAt: "disabled_at",
    createdAt: "created_at",
    targetUrl: "target_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationAwss3$ {
  /** @deprecated use `DestinationAwss3$inboundSchema` instead. */
  export const inboundSchema = DestinationAwss3$inboundSchema;
  /** @deprecated use `DestinationAwss3$outboundSchema` instead. */
  export const outboundSchema = DestinationAwss3$outboundSchema;
  /** @deprecated use `DestinationAwss3$Outbound` instead. */
  export type Outbound = DestinationAwss3$Outbound;
}

export function destinationAwss3ToJSON(
  destinationAwss3: DestinationAwss3,
): string {
  return JSON.stringify(
    DestinationAwss3$outboundSchema.parse(destinationAwss3),
  );
}

export function destinationAwss3FromJSON(
  jsonString: string,
): SafeParseResult<DestinationAwss3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestinationAwss3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestinationAwss3' from JSON`,
  );
}
