/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AzureServiceBusConfig,
  AzureServiceBusConfig$inboundSchema,
  AzureServiceBusConfig$Outbound,
  AzureServiceBusConfig$outboundSchema,
} from "./azureservicebusconfig.js";
import {
  AzureServiceBusCredentials,
  AzureServiceBusCredentials$inboundSchema,
  AzureServiceBusCredentials$Outbound,
  AzureServiceBusCredentials$outboundSchema,
} from "./azureservicebuscredentials.js";
import {
  Topics,
  Topics$inboundSchema,
  Topics$Outbound,
  Topics$outboundSchema,
} from "./topics.js";

/**
 * Type of the destination. Must be 'azure_servicebus'.
 */
export const DestinationCreateAzureServiceBusType = {
  AzureServicebus: "azure_servicebus",
} as const;
/**
 * Type of the destination. Must be 'azure_servicebus'.
 */
export type DestinationCreateAzureServiceBusType = ClosedEnum<
  typeof DestinationCreateAzureServiceBusType
>;

export type DestinationCreateAzureServiceBus = {
  /**
   * Optional user-provided ID. A UUID will be generated if empty.
   */
  id?: string | undefined;
  /**
   * Type of the destination. Must be 'azure_servicebus'.
   */
  type: DestinationCreateAzureServiceBusType;
  /**
   * "*" or an array of enabled topics.
   */
  topics: Topics;
  config: AzureServiceBusConfig;
  credentials: AzureServiceBusCredentials;
};

/** @internal */
export const DestinationCreateAzureServiceBusType$inboundSchema:
  z.ZodNativeEnum<typeof DestinationCreateAzureServiceBusType> = z.nativeEnum(
    DestinationCreateAzureServiceBusType,
  );

/** @internal */
export const DestinationCreateAzureServiceBusType$outboundSchema:
  z.ZodNativeEnum<typeof DestinationCreateAzureServiceBusType> =
    DestinationCreateAzureServiceBusType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationCreateAzureServiceBusType$ {
  /** @deprecated use `DestinationCreateAzureServiceBusType$inboundSchema` instead. */
  export const inboundSchema =
    DestinationCreateAzureServiceBusType$inboundSchema;
  /** @deprecated use `DestinationCreateAzureServiceBusType$outboundSchema` instead. */
  export const outboundSchema =
    DestinationCreateAzureServiceBusType$outboundSchema;
}

/** @internal */
export const DestinationCreateAzureServiceBus$inboundSchema: z.ZodType<
  DestinationCreateAzureServiceBus,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: DestinationCreateAzureServiceBusType$inboundSchema,
  topics: Topics$inboundSchema,
  config: AzureServiceBusConfig$inboundSchema,
  credentials: AzureServiceBusCredentials$inboundSchema,
});

/** @internal */
export type DestinationCreateAzureServiceBus$Outbound = {
  id?: string | undefined;
  type: string;
  topics: Topics$Outbound;
  config: AzureServiceBusConfig$Outbound;
  credentials: AzureServiceBusCredentials$Outbound;
};

/** @internal */
export const DestinationCreateAzureServiceBus$outboundSchema: z.ZodType<
  DestinationCreateAzureServiceBus$Outbound,
  z.ZodTypeDef,
  DestinationCreateAzureServiceBus
> = z.object({
  id: z.string().optional(),
  type: DestinationCreateAzureServiceBusType$outboundSchema,
  topics: Topics$outboundSchema,
  config: AzureServiceBusConfig$outboundSchema,
  credentials: AzureServiceBusCredentials$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationCreateAzureServiceBus$ {
  /** @deprecated use `DestinationCreateAzureServiceBus$inboundSchema` instead. */
  export const inboundSchema = DestinationCreateAzureServiceBus$inboundSchema;
  /** @deprecated use `DestinationCreateAzureServiceBus$outboundSchema` instead. */
  export const outboundSchema = DestinationCreateAzureServiceBus$outboundSchema;
  /** @deprecated use `DestinationCreateAzureServiceBus$Outbound` instead. */
  export type Outbound = DestinationCreateAzureServiceBus$Outbound;
}

export function destinationCreateAzureServiceBusToJSON(
  destinationCreateAzureServiceBus: DestinationCreateAzureServiceBus,
): string {
  return JSON.stringify(
    DestinationCreateAzureServiceBus$outboundSchema.parse(
      destinationCreateAzureServiceBus,
    ),
  );
}

export function destinationCreateAzureServiceBusFromJSON(
  jsonString: string,
): SafeParseResult<DestinationCreateAzureServiceBus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestinationCreateAzureServiceBus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestinationCreateAzureServiceBus' from JSON`,
  );
}
