// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AWSKinesisConfig struct {
	// The name of the AWS Kinesis stream.
	StreamName string `json:"stream_name"`
	// The AWS region where the Kinesis stream is located.
	Region string `json:"region"`
	// Optional. Custom AWS endpoint URL (e.g., for LocalStack or VPC endpoints).
	Endpoint *string `json:"endpoint,omitempty"`
	// Optional. JMESPath template to extract the partition key from the event payload (e.g., `metadata."event-id"`). Defaults to event ID.
	PartitionKeyTemplate *string `json:"partition_key_template,omitempty"`
}

func (o *AWSKinesisConfig) GetStreamName() string {
	if o == nil {
		return ""
	}
	return o.StreamName
}

func (o *AWSKinesisConfig) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *AWSKinesisConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *AWSKinesisConfig) GetPartitionKeyTemplate() *string {
	if o == nil {
		return nil
	}
	return o.PartitionKeyTemplate
}
