// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AWSSQSCredentials struct {
	// AWS Access Key ID.
	Key string `json:"key"`
	// AWS Secret Access Key.
	Secret string `json:"secret"`
	// Optional AWS Session Token (for temporary credentials).
	Session *string `json:"session,omitempty"`
}

func (o *AWSSQSCredentials) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *AWSSQSCredentials) GetSecret() string {
	if o == nil {
		return ""
	}
	return o.Secret
}

func (o *AWSSQSCredentials) GetSession() *string {
	if o == nil {
		return nil
	}
	return o.Session
}
