// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AzureServiceBusCredentials struct {
	// The connection string for the Azure Service Bus namespace.
	ConnectionString string `json:"connection_string"`
}

func (o *AzureServiceBusCredentials) GetConnectionString() string {
	if o == nil {
		return ""
	}
	return o.ConnectionString
}
