// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type DestinationUpdateHookdeck struct {
	// "*" or an array of enabled topics.
	Topics      *Topics              `json:"topics,omitempty"`
	Config      any                  `json:"config,omitempty"`
	Credentials *HookdeckCredentials `json:"credentials,omitempty"`
}

func (d DestinationUpdateHookdeck) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationUpdateHookdeck) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *DestinationUpdateHookdeck) GetTopics() *Topics {
	if o == nil {
		return nil
	}
	return o.Topics
}

func (o *DestinationUpdateHookdeck) GetConfig() any {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *DestinationUpdateHookdeck) GetCredentials() *HookdeckCredentials {
	if o == nil {
		return nil
	}
	return o.Credentials
}
