// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type DestinationUpdateAwss3 struct {
	// "*" or an array of enabled topics.
	Topics      *Topics           `json:"topics,omitempty"`
	Config      *Awss3Config      `json:"config,omitempty"`
	Credentials *Awss3Credentials `json:"credentials,omitempty"`
}

func (d DestinationUpdateAwss3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationUpdateAwss3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *DestinationUpdateAwss3) GetTopics() *Topics {
	if o == nil {
		return nil
	}
	return o.Topics
}

func (o *DestinationUpdateAwss3) GetConfig() *Awss3Config {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *DestinationUpdateAwss3) GetCredentials() *Awss3Credentials {
	if o == nil {
		return nil
	}
	return o.Credentials
}
