// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DestinationUpdateAWSKinesis struct {
	// "*" or an array of enabled topics.
	Topics      *Topics                `json:"topics,omitempty"`
	Config      *AWSKinesisConfig      `json:"config,omitempty"`
	Credentials *AWSKinesisCredentials `json:"credentials,omitempty"`
}

func (o *DestinationUpdateAWSKinesis) GetTopics() *Topics {
	if o == nil {
		return nil
	}
	return o.Topics
}

func (o *DestinationUpdateAWSKinesis) GetConfig() *AWSKinesisConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *DestinationUpdateAWSKinesis) GetCredentials() *AWSKinesisCredentials {
	if o == nil {
		return nil
	}
	return o.Credentials
}
