// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type HookdeckCredentials struct {
	// Hookdeck authentication token.
	Token string `json:"token"`
}

func (o *HookdeckCredentials) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
