// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublishRequest struct {
	// Optional. A unique identifier for the event. If not provided, a UUID will be generated.
	ID *string `json:"id,omitempty"`
	// The ID of the tenant to publish for.
	TenantID *string `json:"tenant_id,omitempty"`
	// Optional. Route event to a specific destination.
	DestinationID *string `json:"destination_id,omitempty"`
	// Topic name for the event. Required if Outpost has been configured with topics.
	Topic *string `json:"topic,omitempty"`
	// Should event delivery be retried on failure.
	EligibleForRetry *bool `json:"eligible_for_retry,omitempty"`
	// Any key-value string pairs for metadata.
	Metadata map[string]string `json:"metadata,omitempty"`
	// Any JSON payload for the event data.
	Data map[string]any `json:"data"`
}

func (o *PublishRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PublishRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *PublishRequest) GetDestinationID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationID
}

func (o *PublishRequest) GetTopic() *string {
	if o == nil {
		return nil
	}
	return o.Topic
}

func (o *PublishRequest) GetEligibleForRetry() *bool {
	if o == nil {
		return nil
	}
	return o.EligibleForRetry
}

func (o *PublishRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *PublishRequest) GetData() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Data
}
