// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RabbitMQCredentials struct {
	// RabbitMQ username.
	Username string `json:"username"`
	// RabbitMQ password.
	Password string `json:"password"`
}

func (o *RabbitMQCredentials) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *RabbitMQCredentials) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}
