// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *Security) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}
