// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
)

type TopicsEnum string

const (
	TopicsEnumWildcard TopicsEnum = "*"
)

func (e TopicsEnum) ToPointer() *TopicsEnum {
	return &e
}
func (e *TopicsEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "*":
		*e = TopicsEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TopicsEnum: %v", v)
	}
}

type TopicsType string

const (
	TopicsTypeTopicsEnum TopicsType = "Topics_enum"
	TopicsTypeArrayOfStr TopicsType = "arrayOfStr"
)

// Topics - "*" or an array of enabled topics.
type Topics struct {
	TopicsEnum *TopicsEnum `queryParam:"inline"`
	ArrayOfStr []string    `queryParam:"inline"`

	Type TopicsType
}

func CreateTopicsTopicsEnum(topicsEnum TopicsEnum) Topics {
	typ := TopicsTypeTopicsEnum

	return Topics{
		TopicsEnum: &topicsEnum,
		Type:       typ,
	}
}

func CreateTopicsArrayOfStr(arrayOfStr []string) Topics {
	typ := TopicsTypeArrayOfStr

	return Topics{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *Topics) UnmarshalJSON(data []byte) error {

	var topicsEnum TopicsEnum = TopicsEnum("")
	if err := utils.UnmarshalJSON(data, &topicsEnum, "", true, true); err == nil {
		u.TopicsEnum = &topicsEnum
		u.Type = TopicsTypeTopicsEnum
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, true); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = TopicsTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Topics", string(data))
}

func (u Topics) MarshalJSON() ([]byte, error) {
	if u.TopicsEnum != nil {
		return utils.MarshalJSON(u.TopicsEnum, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type Topics: all fields are null")
}
