// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

// RateLimitedError - Status codes relating to the client being rate limited by the server
type RateLimitedError struct {
	Message              *string        `json:"message,omitempty"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

var _ error = &RateLimitedError{}

func (e *RateLimitedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
