/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsListDeliveries } from "../../funcs/eventsListDeliveries.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTenantEventDeliveriesRequest$inboundSchema,
};

export const tool$eventsListDeliveries: ToolDefinition<typeof args> = {
  name: "events-list-deliveries",
  description: `List Event Delivery Attempts

Retrieves a list of delivery attempts for a specific event, including response details.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsListDeliveries(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
