/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsListByDestination } from "../../funcs/eventsListByDestination.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTenantEventsByDestinationRequest$inboundSchema,
};

export const tool$eventsListByDestination: ToolDefinition<typeof args> = {
  name: "events-list-by-destination",
  description: `List Events by Destination

Retrieves events associated with a specific destination for the tenant.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsListByDestination(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
