/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsUpsert } from "../../funcs/tenantsUpsert.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpsertTenantRequest$inboundSchema,
};

export const tool$tenantsUpsert: ToolDefinition<typeof args> = {
  name: "tenants-upsert",
  description: `Create or Update Tenant

Idempotently creates or updates a tenant. Required before associating destinations.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tenantsUpsert(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
