// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
)

type GetTenantTokenGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantTokenGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type GetTenantTokenRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantTokenRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type GetTenantTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tenant JWT token.
	TenantToken *components.TenantToken
}

func (o *GetTenantTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTenantTokenResponse) GetTenantToken() *components.TenantToken {
	if o == nil {
		return nil
	}
	return o.TenantToken
}
