/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsEnable } from "../../funcs/destinationsEnable.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EnableTenantDestinationRequest$inboundSchema,
};

export const tool$destinationsEnable: ToolDefinition<typeof args> = {
  name: "destinations-enable",
  description: `Enable Destination

Enables a previously disabled destination.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await destinationsEnable(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
