/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsGetPortalUrlJwtContext } from "../../funcs/tenantsGetPortalUrlJwtContext.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPortalUrlJwtContextRequest$inboundSchema,
};

export const tool$tenantsGetPortalUrlJwtContext: ToolDefinition<typeof args> = {
  name: "tenants-get-portal-url-jwt-context",
  description: `Get Portal Redirect URL (JWT Auth Context)

Returns a redirect URL containing a JWT to authenticate the user with the portal (infers tenant from JWT). Requires Admin API Key.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tenantsGetPortalUrlJwtContext(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
