/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsGetTokenJwtContext } from "../../funcs/tenantsGetTokenJwtContext.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$tenantsGetTokenJwtContext: ToolDefinition = {
  name: "tenants-get-token-jwt-context",
  description: `Get Tenant JWT Token (JWT Auth Context)

Returns a JWT token scoped to the tenant (infers tenant from JWT). Requires Admin API Key.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await tenantsGetTokenJwtContext(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
