"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .destinationupdateawssqs import (
    DestinationUpdateAWSSQS,
    DestinationUpdateAWSSQSTypedDict,
)
from .destinationupdaterabbitmq import (
    DestinationUpdateRabbitMQ,
    DestinationUpdateRabbitMQTypedDict,
)
from .destinationupdatewebhook import (
    DestinationUpdateWebhook,
    DestinationUpdateWebhookTypedDict,
)
from typing import Union
from typing_extensions import TypeAliasType


DestinationUpdateTypedDict = TypeAliasType(
    "DestinationUpdateTypedDict",
    Union[
        DestinationUpdateWebhookTypedDict,
        DestinationUpdateAWSSQSTypedDict,
        DestinationUpdateRabbitMQTypedDict,
    ],
)


DestinationUpdate = TypeAliasType(
    "DestinationUpdate",
    Union[DestinationUpdateWebhook, DestinationUpdateAWSSQS, DestinationUpdateRabbitMQ],
)
