"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .topics_union import TopicsUnion, TopicsUnionTypedDict
from .webhookconfig import WebhookConfig, WebhookConfigTypedDict
from .webhookcredentials import WebhookCredentials, WebhookCredentialsTypedDict
from datetime import datetime
from enum import Enum
from openapi.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class DestinationWebhookType(str, Enum):
    r"""Type of the destination."""

    WEBHOOK = "webhook"


class DestinationWebhookTypedDict(TypedDict):
    id: str
    r"""Control plane generated ID or user provided ID for the destination."""
    type: DestinationWebhookType
    r"""Type of the destination."""
    topics: TopicsUnionTypedDict
    r"""\"*\" or an array of enabled topics."""
    disabled_at: Nullable[datetime]
    r"""ISO Date when the destination was disabled, or null if enabled."""
    created_at: datetime
    r"""ISO Date when the destination was created."""
    config: WebhookConfigTypedDict
    credentials: WebhookCredentialsTypedDict


class DestinationWebhook(BaseModel):
    id: str
    r"""Control plane generated ID or user provided ID for the destination."""

    type: DestinationWebhookType
    r"""Type of the destination."""

    topics: TopicsUnion
    r"""\"*\" or an array of enabled topics."""

    disabled_at: Nullable[datetime]
    r"""ISO Date when the destination was disabled, or null if enabled."""

    created_at: datetime
    r"""ISO Date when the destination was created."""

    config: WebhookConfig

    credentials: WebhookCredentials

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["disabled_at"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
