"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DestinationOAuthRedirectTypedDict(TypedDict):
    redirect_url: NotRequired[str]
    r"""Redirect URL for OAuth flow if applicable during destination update."""


class DestinationOAuthRedirect(BaseModel):
    redirect_url: Optional[str] = None
    r"""Redirect URL for OAuth flow if applicable during destination update."""
