"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPortalURLJwtContextTheme(str, Enum):
    r"""Optional theme preference for the portal."""

    LIGHT = "light"
    DARK = "dark"


class GetPortalURLJwtContextRequestTypedDict(TypedDict):
    theme: NotRequired[GetPortalURLJwtContextTheme]
    r"""Optional theme preference for the portal."""


class GetPortalURLJwtContextRequest(BaseModel):
    theme: Annotated[
        Optional[GetPortalURLJwtContextTheme],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Optional theme preference for the portal."""
