"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, SecurityMetadata
from typing_extensions import Annotated, TypedDict


class ListDestinationTypeSchemasJwtSecurityTypedDict(TypedDict):
    tenant_jwt: str


class ListDestinationTypeSchemasJwtSecurity(BaseModel):
    tenant_jwt: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ]
