"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .destination import Destination, DestinationTypedDict
from .destinationoauthredirect import (
    DestinationOAuthRedirect,
    DestinationOAuthRedirectTypedDict,
)
from .destinationupdate import DestinationUpdate, DestinationUpdateTypedDict
from openapi.types import BaseModel
from openapi.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class UpdateTenantDestinationGlobalsTypedDict(TypedDict):
    tenant_id: NotRequired[str]


class UpdateTenantDestinationGlobals(BaseModel):
    tenant_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None


class UpdateTenantDestinationSecurityTypedDict(TypedDict):
    admin_api_key: NotRequired[str]
    tenant_jwt: NotRequired[str]


class UpdateTenantDestinationSecurity(BaseModel):
    admin_api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    tenant_jwt: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class UpdateTenantDestinationRequestTypedDict(TypedDict):
    destination_id: str
    r"""The ID of the destination."""
    destination_update: DestinationUpdateTypedDict
    tenant_id: NotRequired[str]
    r"""The ID of the tenant. Required when using AdminApiKey authentication."""


class UpdateTenantDestinationRequest(BaseModel):
    destination_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the destination."""

    destination_update: Annotated[
        DestinationUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    tenant_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of the tenant. Required when using AdminApiKey authentication."""


UpdateTenantDestinationResponseTypedDict = TypeAliasType(
    "UpdateTenantDestinationResponseTypedDict",
    Union[DestinationOAuthRedirectTypedDict, DestinationTypedDict],
)
r"""Destination updated successfully or OAuth redirect needed."""


UpdateTenantDestinationResponse = TypeAliasType(
    "UpdateTenantDestinationResponse", Union[DestinationOAuthRedirect, Destination]
)
r"""Destination updated successfully or OAuth redirect needed."""
