// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package outpostgo

// Generated from OpenAPI doc version 0.0.1 and generator version 2.670.1

import (
	"context"
	"fmt"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/config"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/globals"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/hooks"
	"github.com/hookdeck/outpost/sdks/outpost-go/internal/utils"
	"github.com/hookdeck/outpost/sdks/outpost-go/models/components"
	"github.com/hookdeck/outpost/sdks/outpost-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Local development server base path
	"http://localhost:3333/api/v1",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Outpost API: The Outpost API is a REST-based JSON API for managing tenants, destinations, and publishing events.
type Outpost struct {
	SDKVersion string
	// API Health Check
	Health *Health
	// The API segments resources per `tenant`. A tenant represents a user/team/organization in your product. The provided value determines the tenant's ID, which can be any string representation.
	//
	// If your system is not multi-tenant, create a single tenant with a hard-code tenant ID upon initialization. If your system has a single tenant but multiple environments, create a tenant per environment, like `live` and `test`.
	//
	Tenants *Tenants
	// Destinations are the endpoints where events are sent. Each destination is associated with a tenant and can be configured to receive specific event topics.
	//
	// ```json
	// {
	//   "id": "des_12345", // Control plane generated ID or user provided ID
	//   "type": "webhooks", // Type of the destination
	//   "topics": ["user.created", "user.updated"], // Topics of events this destination is eligible for
	//   "config": {
	//     // Destination type specific configuration. Schema of depends on type
	//     "url": "https://example.com/webhooks/user"
	//   },
	//   "credentials": {
	//     // Destination type specific credentials. AES encrypted. Schema depends on type
	//     "secret": "some***********"
	//   },
	//   "disabled_at": null, // null or ISO date if disabled
	//   "created_at": "2024-01-01T00:00:00Z" // Date the destination was created
	// }
	// ```
	//
	// The `topics` array can contain either a list of topics or a wildcard `*` implying that all topics are supported. If you do not wish to implement topics for your application, you set all destination topics to `*`.
	//
	// By default all destination `credentials` are obfuscated and the values cannot be read. This does not apply to the `webhook` type destination secret and each destination can expose their own obfuscation logic.
	//
	Destinations *Destinations
	// Operations for publishing events.
	Publish *Publish
	// Operations for retrieving destination type schemas.
	Schemas *Schemas
	// Operations for retrieving available event topics.
	Topics *Topics
	// Operations related to event history and deliveries.
	Events *Events

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Outpost)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Outpost) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Outpost) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(security components.Security) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

// WithTenantID allows setting the TenantID parameter for all supported operations
func WithTenantID(tenantID string) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.Globals.TenantID = &tenantID
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Outpost) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Outpost {
	sdk := &Outpost{
		SDKVersion: "0.3.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.3.0 2.670.1 0.0.1 github.com/hookdeck/outpost/sdks/outpost-go",
			Globals:    globals.Globals{},
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	currentServerURL, _ := sdk.sdkConfiguration.GetServerDetails()
	serverURL := currentServerURL
	serverURL, sdk.sdkConfiguration.Client = sdk.hooks.SDKInit(currentServerURL, sdk.sdkConfiguration.Client)
	if currentServerURL != serverURL {
		sdk.sdkConfiguration.ServerURL = serverURL
	}

	sdk.Health = newHealth(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Tenants = newTenants(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Destinations = newDestinations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Publish = newPublish(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Schemas = newSchemas(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Topics = newTopics(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Events = newEvents(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
