// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"client/models/components"
)

type CreateTenantDestinationGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *CreateTenantDestinationGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type CreateTenantDestinationRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID          *string                      `pathParam:"style=simple,explode=false,name=tenant_id"`
	DestinationCreate components.DestinationCreate `request:"mediaType=application/json"`
}

func (o *CreateTenantDestinationRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *CreateTenantDestinationRequest) GetDestinationCreate() components.DestinationCreate {
	if o == nil {
		return components.DestinationCreate{}
	}
	return o.DestinationCreate
}

func (o *CreateTenantDestinationRequest) GetDestinationCreateWebhook() *components.DestinationCreateWebhook {
	return o.GetDestinationCreate().DestinationCreateWebhook
}

func (o *CreateTenantDestinationRequest) GetDestinationCreateAwsSqs() *components.DestinationCreateAWSSQS {
	return o.GetDestinationCreate().DestinationCreateAWSSQS
}

func (o *CreateTenantDestinationRequest) GetDestinationCreateRabbitmq() *components.DestinationCreateRabbitMQ {
	return o.GetDestinationCreate().DestinationCreateRabbitMQ
}

func (o *CreateTenantDestinationRequest) GetDestinationCreateHookdeck() *components.DestinationCreateHookdeck {
	return o.GetDestinationCreate().DestinationCreateHookdeck
}

func (o *CreateTenantDestinationRequest) GetDestinationCreateAwsKinesis() *components.DestinationCreateAWSKinesis {
	return o.GetDestinationCreate().DestinationCreateAWSKinesis
}

type CreateTenantDestinationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Destination created successfully.
	Destination *components.Destination
}

func (o *CreateTenantDestinationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTenantDestinationResponse) GetDestination() *components.Destination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *CreateTenantDestinationResponse) GetDestinationWebhook() *components.DestinationWebhook {
	if v := o.GetDestination(); v != nil {
		return v.DestinationWebhook
	}
	return nil
}

func (o *CreateTenantDestinationResponse) GetDestinationAwsSqs() *components.DestinationAWSSQS {
	if v := o.GetDestination(); v != nil {
		return v.DestinationAWSSQS
	}
	return nil
}

func (o *CreateTenantDestinationResponse) GetDestinationRabbitmq() *components.DestinationRabbitMQ {
	if v := o.GetDestination(); v != nil {
		return v.DestinationRabbitMQ
	}
	return nil
}

func (o *CreateTenantDestinationResponse) GetDestinationHookdeck() *components.DestinationHookdeck {
	if v := o.GetDestination(); v != nil {
		return v.DestinationHookdeck
	}
	return nil
}

func (o *CreateTenantDestinationResponse) GetDestinationAwsKinesis() *components.DestinationAWSKinesis {
	if v := o.GetDestination(); v != nil {
		return v.DestinationAWSKinesis
	}
	return nil
}
