// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type DeleteTenantDestinationGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *DeleteTenantDestinationGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type DeleteTenantDestinationSecurity struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *DeleteTenantDestinationSecurity) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *DeleteTenantDestinationSecurity) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}

type DeleteTenantDestinationRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// The ID of the destination.
	DestinationID string `pathParam:"style=simple,explode=false,name=destination_id"`
}

func (o *DeleteTenantDestinationRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DeleteTenantDestinationRequest) GetDestinationID() string {
	if o == nil {
		return ""
	}
	return o.DestinationID
}

type DeleteTenantDestinationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success confirmation.
	SuccessResponse *components.SuccessResponse
}

func (o *DeleteTenantDestinationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteTenantDestinationResponse) GetSuccessResponse() *components.SuccessResponse {
	if o == nil {
		return nil
	}
	return o.SuccessResponse
}
