// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"client/models/components"
)

type GetTenantGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type GetTenantRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type GetTenantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tenant details.
	Tenant *components.Tenant
}

func (o *GetTenantResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTenantResponse) GetTenant() *components.Tenant {
	if o == nil {
		return nil
	}
	return o.Tenant
}
