// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetTenantEventGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantEventGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type GetTenantEventSecurity struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *GetTenantEventSecurity) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *GetTenantEventSecurity) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}

type GetTenantEventRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// The ID of the event.
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

func (o *GetTenantEventRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *GetTenantEventRequest) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

type GetTenantEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Event details.
	Event *components.Event
}

func (o *GetTenantEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTenantEventResponse) GetEvent() *components.Event {
	if o == nil {
		return nil
	}
	return o.Event
}
