// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"client/models/components"
	"encoding/json"
	"fmt"
)

type GetTenantPortalURLGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantPortalURLGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

// Theme - Optional theme preference for the portal.
type Theme string

const (
	ThemeLight Theme = "light"
	ThemeDark  Theme = "dark"
)

func (e Theme) ToPointer() *Theme {
	return &e
}
func (e *Theme) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "light":
		fallthrough
	case "dark":
		*e = Theme(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Theme: %v", v)
	}
}

type GetTenantPortalURLRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Optional theme preference for the portal.
	Theme *Theme `queryParam:"style=form,explode=true,name=theme"`
}

func (o *GetTenantPortalURLRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *GetTenantPortalURLRequest) GetTheme() *Theme {
	if o == nil {
		return nil
	}
	return o.Theme
}

type GetTenantPortalURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Portal redirect URL.
	PortalRedirect *components.PortalRedirect
}

func (o *GetTenantPortalURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTenantPortalURLResponse) GetPortalRedirect() *components.PortalRedirect {
	if o == nil {
		return nil
	}
	return o.PortalRedirect
}
