// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetTenantTokenJwtContextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tenant JWT token.
	TenantToken *components.TenantToken
}

func (o *GetTenantTokenJwtContextResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTenantTokenJwtContextResponse) GetTenantToken() *components.TenantToken {
	if o == nil {
		return nil
	}
	return o.TenantToken
}
