// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetTenantDestinationGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *GetTenantDestinationGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type GetTenantDestinationSecurity struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *GetTenantDestinationSecurity) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *GetTenantDestinationSecurity) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}

type GetTenantDestinationRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// The ID of the destination.
	DestinationID string `pathParam:"style=simple,explode=false,name=destination_id"`
}

func (o *GetTenantDestinationRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *GetTenantDestinationRequest) GetDestinationID() string {
	if o == nil {
		return ""
	}
	return o.DestinationID
}

type GetTenantDestinationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Destination details.
	Destination *components.Destination
}

func (o *GetTenantDestinationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTenantDestinationResponse) GetDestination() *components.Destination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *GetTenantDestinationResponse) GetDestinationWebhook() *components.DestinationWebhook {
	if v := o.GetDestination(); v != nil {
		return v.DestinationWebhook
	}
	return nil
}

func (o *GetTenantDestinationResponse) GetDestinationAwsSqs() *components.DestinationAWSSQS {
	if v := o.GetDestination(); v != nil {
		return v.DestinationAWSSQS
	}
	return nil
}

func (o *GetTenantDestinationResponse) GetDestinationRabbitmq() *components.DestinationRabbitMQ {
	if v := o.GetDestination(); v != nil {
		return v.DestinationRabbitMQ
	}
	return nil
}
