// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type HealthCheckResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Service is healthy.
	Res *string
}

func (o *HealthCheckResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *HealthCheckResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}
