// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"client/models/components"
)

type ListTopicsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of topic names.
	Strings []string
}

func (o *ListTopicsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListTopicsResponse) GetStrings() []string {
	if o == nil {
		return nil
	}
	return o.Strings
}
