// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type ListTenantDestinationTypeSchemasGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *ListTenantDestinationTypeSchemasGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type ListTenantDestinationTypeSchemasSecurity struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *ListTenantDestinationTypeSchemasSecurity) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *ListTenantDestinationTypeSchemasSecurity) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}

type ListTenantDestinationTypeSchemasRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *ListTenantDestinationTypeSchemasRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type ListTenantDestinationTypeSchemasResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of destination type schemas.
	DestinationTypeSchemas []components.DestinationTypeSchema
}

func (o *ListTenantDestinationTypeSchemasResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListTenantDestinationTypeSchemasResponse) GetDestinationTypeSchemas() []components.DestinationTypeSchema {
	if o == nil {
		return nil
	}
	return o.DestinationTypeSchemas
}
