// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"openapi/internal/utils"
	"openapi/models/components"
)

type ListTenantEventsGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *ListTenantEventsGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type ListTenantEventsSecurity struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *ListTenantEventsSecurity) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *ListTenantEventsSecurity) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}

type DestinationIDType string

const (
	DestinationIDTypeStr        DestinationIDType = "str"
	DestinationIDTypeArrayOfStr DestinationIDType = "arrayOfStr"
)

// DestinationID - Filter events by destination ID(s).
type DestinationID struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type DestinationIDType
}

func CreateDestinationIDStr(str string) DestinationID {
	typ := DestinationIDTypeStr

	return DestinationID{
		Str:  &str,
		Type: typ,
	}
}

func CreateDestinationIDArrayOfStr(arrayOfStr []string) DestinationID {
	typ := DestinationIDTypeArrayOfStr

	return DestinationID{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *DestinationID) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = DestinationIDTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, true); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = DestinationIDTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DestinationID", string(data))
}

func (u DestinationID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type DestinationID: all fields are null")
}

// ListTenantEventsStatus - Filter events by delivery status.
type ListTenantEventsStatus string

const (
	ListTenantEventsStatusSuccess ListTenantEventsStatus = "success"
	ListTenantEventsStatusFailed  ListTenantEventsStatus = "failed"
)

func (e ListTenantEventsStatus) ToPointer() *ListTenantEventsStatus {
	return &e
}
func (e *ListTenantEventsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "failed":
		*e = ListTenantEventsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTenantEventsStatus: %v", v)
	}
}

type ListTenantEventsRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Filter events by destination ID(s).
	DestinationID *DestinationID `queryParam:"style=form,explode=true,name=destination_id"`
	// Filter events by delivery status.
	Status *ListTenantEventsStatus `queryParam:"style=form,explode=true,name=status"`
}

func (o *ListTenantEventsRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *ListTenantEventsRequest) GetDestinationID() *DestinationID {
	if o == nil {
		return nil
	}
	return o.DestinationID
}

func (o *ListTenantEventsRequest) GetStatus() *ListTenantEventsStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type ListTenantEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of events.
	Events []components.Event
}

func (o *ListTenantEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListTenantEventsResponse) GetEvents() []components.Event {
	if o == nil {
		return nil
	}
	return o.Events
}
