// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"client/models/components"
)

type ListDestinationTypeSchemasJwtResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of destination type schemas.
	DestinationTypeSchemas []components.DestinationTypeSchema
}

func (o *ListDestinationTypeSchemasJwtResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListDestinationTypeSchemasJwtResponse) GetDestinationTypeSchemas() []components.DestinationTypeSchema {
	if o == nil {
		return nil
	}
	return o.DestinationTypeSchemas
}
