// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"client/models/components"
)

type PublishEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PublishEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
