// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type RetryTenantEventGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *RetryTenantEventGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type RetryTenantEventSecurity struct {
	AdminAPIKey *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TenantJwt   *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *RetryTenantEventSecurity) GetAdminAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.AdminAPIKey
}

func (o *RetryTenantEventSecurity) GetTenantJwt() *string {
	if o == nil {
		return nil
	}
	return o.TenantJwt
}

type RetryTenantEventRequest struct {
	// The ID of the tenant. Required when using AdminApiKey authentication.
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// The ID of the destination.
	DestinationID string `pathParam:"style=simple,explode=false,name=destination_id"`
	// The ID of the event to retry.
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

func (o *RetryTenantEventRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *RetryTenantEventRequest) GetDestinationID() string {
	if o == nil {
		return ""
	}
	return o.DestinationID
}

func (o *RetryTenantEventRequest) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

type RetryTenantEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *RetryTenantEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
